# Site settings
title: jTags
email: your-email@domain.com
description: "Embed custom functionlity into HTML tags with jTags."
baseurl: "http://matantsu.github.io/jTags/"
url: "http://matantsu.github.io/jTags/"
twitter_username: jekyllrb
github_username:   matantsu

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3 
